hashed_message = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
signing_address = ""
tx_hash = ""
verifying_address = ""
