amount = ""
chainId = ""
domain = ""
passcode = ""
reqDomain = ""
serverHash = ""
signing_address = ""
txHash = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
tx_type = ""
