amount = ""
chainId = ""
domain = ""
serverHash = ""
signing_address = ""
txHash = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
tx_type = ""
verifying_address = ""
